// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDGWrN1FhhcJm-zLM2BoCBZ1P_p4gzkLQ',
    appId: '1:930014640356:web:624fbbdddba6a3f2e114f1',
    messagingSenderId: '930014640356',
    projectId: 'brainbites-bfd47',
    authDomain: 'brainbites-bfd47.firebaseapp.com',
    storageBucket: 'brainbites-bfd47.appspot.com',
    measurementId: 'G-XG7E5GWHSW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUw4bnF5gi-RAZ0FirLC4FSvD4Flzyte4',
    appId: '1:930014640356:android:2c6beddd1bd78fc3e114f1',
    messagingSenderId: '930014640356',
    projectId: 'brainbites-bfd47',
    storageBucket: 'brainbites-bfd47.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbLLvmfT_u-0hcr2X5Hmhky50vUS6j28k',
    appId: '1:930014640356:ios:b979e6c3a523224ee114f1',
    messagingSenderId: '930014640356',
    projectId: 'brainbites-bfd47',
    storageBucket: 'brainbites-bfd47.appspot.com',
    androidClientId: '930014640356-ve85732eoejtl99j50ike8svqfeuregj.apps.googleusercontent.com',
    iosClientId: '930014640356-rqsi00ubr1ntprlmvvkm1iu50ljd5avi.apps.googleusercontent.com',
    iosBundleId: 'com.example.brainbites',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbLLvmfT_u-0hcr2X5Hmhky50vUS6j28k',
    appId: '1:930014640356:ios:b979e6c3a523224ee114f1',
    messagingSenderId: '930014640356',
    projectId: 'brainbites-bfd47',
    storageBucket: 'brainbites-bfd47.appspot.com',
    androidClientId: '930014640356-ve85732eoejtl99j50ike8svqfeuregj.apps.googleusercontent.com',
    iosClientId: '930014640356-rqsi00ubr1ntprlmvvkm1iu50ljd5avi.apps.googleusercontent.com',
    iosBundleId: 'com.example.brainbites',
  );
}
